# Generated by Django 3.2.4 on 2021-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
